// <auto-generated />
namespace Contoso.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class CreateJunction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateJunction));
        
        string IMigrationMetadata.Id
        {
            get { return "201910170314519_CreateJunction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
